Assistability/PresentationMVC/Controllers/PerformanceController.cs
/// <summary>
/// Ryan Taylor
/// Created: 2021/04/07
///
/// contains all the methods to work the website performaces
/// </summary>
///
/// <remarks>
/// Ryan Taylor
/// Updated: 2021/04/24
/// Adding in performance event functions
/// </remarks>
/// 
using DataStorageModels;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationHelpers;

namespace PresentationMVC.Controllers
{
    [Authorize]
    public class PerformanceController : Controller
    {
        private PerformanceManager _performanceManager = new PerformanceManager();
        private UserManager _userManager = new UserManager();
        private PerformanceEventManager _performanceEventManager = new PerformanceEventManager();

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for desplaying a clients performances
        /// </summary>
        ///<exception>if something goes wrong</exception>
        ///<returns>a rederect to a list of active performances for a client
        ///or to an error screen if failed</returns>
        public ActionResult Performances()
        {
            try
            {
                UserAccount _selectedUser = AccountController.GetSelectedUserAccount(HttpContext); //User.Identity.Name
                ViewBag.User = _selectedUser;
                ViewBag.Active = true;
                return View(
                    _performanceManager.RetrievePerformancesByClientAndActive(
                        _selectedUser.UserAccountID, true));
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for desplaying a clients performances by active or not active
        /// </summary>
        ///<param name="selectedUserId">the user id of the client</param>
        ///<param name="activeInactive">the active feild</param>
        ///<exception>if something goes wrong</exception>
        ///<returns>a rederect to a list of active or inative performances for a client
        ///or to an error screen if failed</returns>
        public ActionResult PerformancesByActive(int selectedUserId, bool activeInactive)
        {
            try
            {
                ViewBag.Active = activeInactive;
                ViewBag.User = _userManager.GetUserAccountByUserAccountID(selectedUserId);
                return View(
                    _performanceManager.RetrievePerformancesByClientAndActive(
                        selectedUserId, activeInactive));
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for desplaying the details of a performance
        /// </summary>
        ///<param name="performanceName">the name of the performance to be edited</param>
        ///<param name="clientId">the id of the client the perfomance is for</param>
        ///<exception>if something goes wrong</exception>
        ///<returns>a rederect to performance details page  
        ///or to an error screen if failed</returns>
        public ActionResult Details(string performanceName, int clientId)
        {
            try
            {
                var performanceList = _performanceManager.RetrievePerformancesByClient(clientId);
                var onePerformance =
                    performanceList.Where(p => p.PerformanceName == performanceName).ToList();
                Performance performance = onePerformance[0];
                return View(performance);
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for desplaying a list of a performance to edit
        /// </summary>
        ///<exception>if something goes wrong</exception>
        ///<returns>a view of editable list of performances 
        ///or to an error screen if failed</returns>
        public ActionResult EditablePerformances(int SelectedId)
        {
            try
            {
                UserAccount _selectedUser = _userManager.GetUserAccountByUserAccountID(SelectedId); //SelectUserAccountByEmail(AccountController.GetSelectedUserAccountVM(HttpContext).Email);
                ViewBag.User = _selectedUser;
                return View(
                    _performanceManager.RetrievePerformancesByClient(
                        _selectedUser.UserAccountID));
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for deactivating and reactivating a performance
        /// </summary>
        ///<param name="performanceName">the name of the performance to be edited</param>
        ///<param name="clientId">the id of the client the perfomance is for</param>
        ///<param name="oldActive">the original active variable</param>
        ///<param name="newActive">the new active variable</param>
        ///<exception>if something goes wrong</exception>
        ///<returns>a rederect to the editable list of performances 
        ///or to an error screen if failed</returns>
        public ActionResult ActiveDeactive(string performanceName, int clientId, 
            bool oldActive, bool newActive)
        {
            try
            {
                _performanceManager.DeactivateReactivatePerformance(performanceName, clientId,
                    oldActive, newActive);
                return RedirectToAction("EditablePerformances", new { SelectedId = clientId });
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for setting up a performance editing page
        /// </summary>
        ///<param name="performanceName">the name of the performance to be edited</param>
        ///<param name="clientId">the id of the client the perfomance is for</param>
        ///<returns>a rederect to an edit view or to an error screen if failed</returns>
        public ActionResult PopulateEdit(string performanceName, int clientId)
        {
            try
            {
                var performanceList = _performanceManager.RetrievePerformancesByClient(clientId);
                var onePerformance =
                    performanceList.Where(p => p.PerformanceName == performanceName).ToList();
                Performance performance = onePerformance[0];
                return View(performance);
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for editing a performance
        /// </summary>
        ///<param name="update">information fit into a perfomance model 
        ///from the form to update a performance</param>
        ///<exception>if the description is to long or short</exception>
        ///<returns>a rederect to the edit list on compeation or to an error screen if failed</returns>
        [HttpPost]
        public ActionResult EditPerformance(Performance update) 
        {
            try
            {

                UserAccount _selectedUser = _userManager.GetUserAccountByUserAccountID(update.UserID_client); //.SelectUserAccountByEmail(AccountController.GetSelectedUserAccountVM(HttpContext).Email);
                if (!update.PerformanceDescription.IsValidPerformanceDescription())
                {
                    return RedirectToAction("Error", "Home", new { errorMessage =
                        update.PerformanceDescription +
                        " is not a valid Performance descriotion (255 characters max)"
                    });
                }
                var performanceList =
                    _performanceManager.RetrievePerformancesByClient(_selectedUser.UserAccountID);
                var onePerformance = performanceList.Where(p => p.PerformanceName ==
                    update.PerformanceName).ToList();
                Performance oldPerformance = onePerformance[0];

                _performanceManager.EditePerformance(oldPerformance.PerformanceName,
                update.PerformanceDescription, oldPerformance.UserID_client,
                oldPerformance.PerformanceDescription, oldPerformance.UserID_client);

                return RedirectToAction("EditablePerformances", new { SelectedId = update.UserID_client});
            }
            catch (Exception ex)
            {
                string error = ex.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        /// <summary>
        /// Ryan Taylor
        /// Created: 2021/04/01
        ///
        /// a method for setting up a new performance
        /// </summary>
        ///<returns>a view to create a performance</returns>

Assistability/PresentationMVC/Views/Performance/Create.cshtml
@model DataStorageModels.Performance
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h4>@Html.ActionLink("Manage Performances", "Performances", "Performance") &nbsp;|&nbsp; @Html.ActionLink("Edit Performances", "EditablePerformances", new { SelectedId = Model.UserID_client })</h4>

@using (Html.BeginForm("AddNewPerformance", "Performance", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="display:inline-block">
        <h4>Performance</h4>
        <hr />
        @Html.HiddenFor(model => model.UserID_client, Model.UserID_client)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceName, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 37.5%; text - align: left" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PerformanceName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.PerformanceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" >
            @Html.LabelFor(model => model.PerformanceDescription, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 47%; text - align: left" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PerformanceDescription, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.PerformanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Index", "Home")
</div>

Assistability/PresentationMVC/Views/Performance/CreatePerformanceEvent.cshtml
@model DataStorageModels.PerformanceEvent

@{
    ViewBag.Title = "CreatePerformanceEvent";
}

<h2>CreatePerformanceEvent</h2>


@using (Html.BeginForm("AddPerformanceEvent", "Performance", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="display:inline-block">
        <h4>PerformanceEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div >
            <div>
                @Html.HiddenFor(model => model.PerformanceName, Model.PerformanceName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 30%" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventResult, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 30%" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventResult, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventResult, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            <div >
                @Html.HiddenFor(model => model.UserIDClient, Model.UserIDClient)
            </div>
        </div>

        <div >
            <div>
                @Html.HiddenFor(model => model.UserIDReporter, Model.UserIDReporter)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Performance Events", "PerformanceEvents", new { Name = Model.PerformanceName, SelectedId = Model.UserIDClient})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assistability/PresentationMVC/Views/Performance/Details.cshtml
@model DataStorageModels.Performance

@{
    ViewBag.Title = Model.PerformanceName+" Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Performance</h4>
    <hr />
    <dl class="dl-horizontal" style="display:inline-block">
        <dt style="width: 170px;">
            @Html.DisplayNameFor(model => model.PerformanceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformanceName)
        </dd>

        <dt style="width: 170px;">
            @Html.DisplayNameFor(model => model.PerformanceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformanceDescription)
        </dd>

        <dt style="width: 170px;">
            @Html.DisplayNameFor(model => model.PerformanceEntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformanceEntryDate)
        </dd>

        <dt style="width: 170px;">
            @Html.DisplayNameFor(model => model.PerformanceEditDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformanceEditDate)
        </dd>

        <dt style="width: 170px;">
            @Html.DisplayNameFor(model => model.PerformanceRemovalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformanceRemovalDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Performances")
</p>

Assistability/PresentationMVC/Views/Performance/EditPerformanceEvent.cshtml
@model DataStorageModels.PerformanceEvent

@{
    ViewBag.Title = "EditPerformanceEvent";
    IEnumerable<String> performanceNames = (IEnumerable<String>)ViewBag.PerformanceNames;
}

<h2>EditPerformanceEvent</h2>


@using (Html.BeginForm("UpdatePerformanceEvent", "Performance", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal" style="display:inline-block">
    <h4>PerformanceEvent</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PerformanceEventID)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.DateOfOccurance)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EventEditDate)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserIDClient)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserIDReporter)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PerformanceName)

    <div class="form-group">
        @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 40%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventResult, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 40%; text-align: left;" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventResult, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventResult, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Performance Events", "PerformanceEvents", new { Name = Model.PerformanceName, SelectedId = Model.UserIDClient })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assistability/PresentationMVC/Views/Performance/EditablePerformances.cshtml
@model IEnumerable<DataStorageModels.Performance>

@{
    ViewBag.Title = "EditablePerformances";
}

<h2>Editable Performances</h2>
<h4>@Html.ActionLink("Manage Performances", "Performances", "Performance") &nbsp;|&nbsp; @Html.ActionLink("Create A Performance", "Create", new { SelectedId = ViewBag.User.UserAccountID })</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @{
                    if (item.Active)
                    {
                        @Html.ActionLink("Deactivate", "ActiveDeactive", new
                        {
                       performanceName = item.PerformanceName,
                            clientId = item.UserID_client,
                       oldActive = item.Active,
                            newActive = !item.Active
                        })
                    }
                    else
                    {
                        @Html.ActionLink("Activate", "ActiveDeactive", new
                        {
                       performanceName = item.PerformanceName,
                            clientId = item.UserID_client,
                       oldActive = item.Active,
                            newActive = !item.Active
                        })
                    }
                }
                | @Html.ActionLink("Edit", "PopulateEdit", new
                {
                    performanceName = item.PerformanceName,
               clientId = item.UserID_client
                })
            </td>
        </tr>
    }

</table>

Assistability/PresentationMVC/Views/Performance/PerformanceEvents.cshtml
@model IEnumerable<DataStorageModels.PerformanceEvent>

@{
    ViewBag.Title = "PerformanceEvents";
}

<h2>@ViewBag.Performance.PerformanceName Performance Events</h2>

<p>
    @Html.ActionLink("Create New Performance Event", "CreatePerformanceEvent", new { Name = ViewBag.Performance.PerformanceName, SelectedId = ViewBag.Performance.UserID_client })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventResult)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventResult)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditPerformanceEvent", new { id=item.PerformanceEventID, Name = item.PerformanceName, SelectedUserId = item.UserIDClient })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Back to Performances", "Performances")
</p>

Assistability/PresentationMVC/Views/Performance/Performances.cshtml
@model IEnumerable<DataStorageModels.Performance>

@{
    ViewBag.Title = ViewBag.User.FirstName + " " + " " + ViewBag.User.LastName + "'s Performances";
}
<h2>@ViewBag.Title</h2>
<h4>@Html.ActionLink("Create A Performance", "Create", new { SelectedId = ViewBag.User.UserAccountID }) &nbsp;|&nbsp; @Html.ActionLink("Edit Performances", "EditablePerformances", new { SelectedId = ViewBag.User.UserAccountID })</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceDescription)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new
                {
                    performanceName = item.PerformanceName
               ,
                    clientId = item.UserID_client
                }) |
                @Html.ActionLink("Performance Events", "PerformanceEvents", new { Name = item.PerformanceName, SelectedId = item.UserID_client })
            </td>
        </tr>
    }

</table>
<p>
    @{
        if (ViewBag.Active)
        {
            @Html.ActionLink("Not Active", "PerformancesByActive", new
            {
           selectedUserId = ViewBag.User.UserAccountID,
                activeInactive = !ViewBag.Active
            })
        }
        else
        {
            @Html.ActionLink("Active", "PerformancesByActive", new
            {
           selectedUserId = ViewBag.User.UserAccountID,
                activeInactive = !ViewBag.Active
            })
        }
    }
</p>

Assistability/PresentationMVC/Views/Performance/PerformancesByActive.cshtml
@model IEnumerable<DataStorageModels.Performance>

@{
    ViewBag.Title = ViewBag.User.FirstName + " " + " " + ViewBag.User.LastName + "'s Performances";
}

<h2>@ViewBag.Title</h2>
<h4>@Html.ActionLink("Create A Performance", "Create", new { SelectedId = ViewBag.User.UserAccountID }) &nbsp;|&nbsp; @Html.ActionLink("Edit Performances", "EditablePerformances", new { SelectedId = ViewBag.User.UserAccountID })</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceDescription)
            </td>
            <td>
                @Html.ActionLink("Details", "Details",
               new { performanceName = item.PerformanceName, clientId = item.UserID_client }) |
                @Html.ActionLink("Performance Events", "PerformanceEvents", new { Name = item.PerformanceName, SelectedId = item.UserID_client })
            </td>
        </tr>
    }

</table>
<p>
    @{
        if (ViewBag.Active)
        {
            @Html.ActionLink("Not Active", "PerformancesByActive", new
            {
                selectedUserId =
           ViewBag.User.UserAccountID,
                activeInactive = !ViewBag.Active
            })
        }
        else
        {
            @Html.ActionLink("Active", "PerformancesByActive", new
            {
                selectedUserId =
           ViewBag.User.UserAccountID,
                activeInactive = !ViewBag.Active
            })
        }
    }
</p>

Assistability/PresentationMVC/Views/Performance/PopulateEdit.cshtml
@model DataStorageModels.Performance

@{
    ViewBag.Title = "Edit "+Model.PerformanceName;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("EditPerformance", "Performance", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="display:inline-block">
        <h4>Performance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID_client, Model.UserID_client)
        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceName, "Performance Name", htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 38%" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PerformanceName, new { htmlAttributes = new { @class = "form-control" }, @readonly = "readonly", @style = "width: 90%; text-align: center" })
                @Html.ValidationMessageFor(model => model.PerformanceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PerformanceDescription, "Performance Description", htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 48%; text-align: center" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PerformanceDescription, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.PerformanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "EditablePerformances", new { SelectedId = Model.UserID_client})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}