Assistability/PresentationMVC/Controllers/IncidentEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataStorageModels;
using LogicLayer;
using PresentationHelpers;

namespace PresentationMVC.Controllers
{
    public class IncidentEventController : Controller
    {

        private IncidentEventManager _incidentEventManger = new IncidentEventManager();
        private IncidentManager _incidentManager = new IncidentManager();
        private UserManager _userManager = new UserManager();
        private Incident _selectedIncident = new Incident();
        private UserAccount _selectedUser = new UserAccount();
        private UserAccount _currentUser = new UserAccount();

        // GET: IncidentEvent
      public IncidentEventController()
        {

        }

        /// <summary>
        /// NickLoesel
        /// Created: 2021/04/28
        ///
        /// a method for displaying incident events
        /// </summary>
        ///<param name="selectedUserId">the user id of the client</param>
        ///<param name="incidentName">the active feild</param>
        ///<exception>if something goes wrong</exception>
        ///<returns>a rederect to a list of active or inative performances for a client
        ///or to an error screen if failed</returns>
        public ActionResult IncidentEvents(string incidentName)
        {
            try
            {
                UserAccount _selectedUser = AccountController.GetSelectedUserAccount(HttpContext);
                UserAccount _currentUser = AccountController.GetAuthenticatedUserAccount(HttpContext);
                ViewBag.User = _userManager.GetUserAccountByUserAccountID(_selectedUser.UserAccountID);
                ViewBag.IncidentName = incidentName;
                return View(_incidentEventManger.SelectIncidentsEventsByIncidentName(incidentName));
            }
            catch (Exception ex)
            {
                string error = ex.Message + "\n\n" + ex.InnerException.Message;
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        public ActionResult Create(string incidentName) //int clientId, int creatorId
        {
            ViewBag.IncidentName = incidentName;
            return View();
        }

        public ActionResult Delete(int incidentEventId)
        {
            return View(_incidentEventManger.SelectIncidentEventById(incidentEventId));
        }
           
        /// <summary>
        /// NickLoesel
        /// Created: 2021/04/15
        ///
        /// a method for creating a new incident event
        /// </summary>
        ///<param name="model">information fit into a incident event model from the form 
        ///to create an incident</param>
        ///<exception>if the incident name is already in use by the same client and 
        ///if the name or description is to long or short</exception>
        ///<returns>a rederect to perfomance list on compeation or to an error screen if failed</returns>
        [HttpPost]
        public ActionResult AddNewIncidentEvent(IncidentEvent model)
        {
            try
            {
                UserAccount _selectedUser = AccountController.GetSelectedUserAccount(HttpContext);
                UserAccount _currentUser = AccountController.GetAuthenticatedUserAccount(HttpContext);
                if (!model.EventConsequence.IsValidEventConsquence())
                {
                    return RedirectToAction("Error", "Home", new
                    {
                        errorMessage =
                        model.EventConsequence +
                        " is not a valid event consequence. (500 characters max)"
                    });
                }
                if (!model.PersonsInvolved.IsValidPersonsInvolved())
                {
                    return RedirectToAction("Error", "Home", new
                    {
                        errorMessage =
                        model.PersonsInvolved +
                        " is not a valid value for persons involved. (250 characters max)"
                    });
                }
                if (!model.EventDescription.IsValidEventDescription())
                {
                    return RedirectToAction("Error", "Home", new
                    {
                        errorMessage =
                        model.EventDescription +
                        " is not a valid desired consequence (250 characters max)"
                    });
                }
                IncidentEvent newIncidentEvent = new IncidentEvent(model.IncidentName, model.DateOfOccurence , model.PersonsInvolved,
                    model.EventDescription, model.EventConsequence, null, _selectedUser.UserAccountID,
                    _currentUser.UserAccountID);
                _incidentEventManger.InsertNewIncidentEvent(newIncidentEvent);
                return RedirectToAction("Incidents", "Incident");
            }
            catch (Exception ex)
            {
                string error = ex.Message + "\n\n" + ex.InnerException.Message;
                if (ex.InnerException.Message.Contains("pk"))
                {
                    error = "You already have an incident "
                        + model.IncidentName + " for this client.";
                }
                return RedirectToAction("Error", "Home", new { errorMessage = error });
            }
        }

        [HttpPost]
        public ActionResult DeleteIncidentEvent(IncidentEvent model)
        {
            try
            {
                _incidentEventManger.DeleteIncidentEvent(model.IncidentEventID);
            }
            catch (Exception ex)
            {
                string error = ex.Message + "\n\n" + ex.InnerException.Message;
                error = "There was an error deleting the supplied incident event.";
                return RedirectToAction("Error", "Home", new { errorMessage = error });

            }
            return RedirectToAction("Incidents", "Incident");
        }
    }
}

Assistability/PresentationMVC/Views/IncidentEvent/Create.cshtml
@model DataStorageModels.IncidentEvent

@{
    ViewBag.Title = "Create";
    string incidentName = string.Format(ViewBag.IncidentName);
    
}

<h2>Create</h2>


@using (Html.BeginForm("AddNewIncidentEvent", "IncidentEvent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="display:inline-block">
    <h4>IncidentEvent</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.IncidentName, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 20%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IncidentName, new { htmlAttributes = new { @class = "control-label col-md-2  ", @readonly = "readonly", @Value = incidentName, @style = "width: 50%; text-align: center" } })
            @Html.ValidationMessageFor(model => model.IncidentName,  "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateOfOccurence, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 20%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfOccurence, new { htmlAttributes = new { @class = "control-label col-md-2  ", @type = "date", @style = "width: 60%; text-align: center" } })
            @Html.ValidationMessageFor(model => model.DateOfOccurence, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PersonsInvolved, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 20%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PersonsInvolved, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PersonsInvolved, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 20%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventConsequence, htmlAttributes: new { @class = "control-label col-md-2", @style = "width: 20%" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventConsequence, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventConsequence, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to Incident Events", "Incidents", "Incident")
</div>

Assistability/PresentationMVC/Views/IncidentEvent/Delete.cshtml
@model DataStorageModels.IncidentEvent


<h2>Delete Incident Event</h2>

<h3 style="color: red">Are you sure you want to delete this Incident Event? It will be lost FOREVER.</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="display:inline-block">
        <dt>
            @Html.DisplayNameFor(model => model.IncidentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncidentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfOccurence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfOccurence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonsInvolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonsInvolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventConsequence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventConsequence)
        </dd>



    </dl>

    @using (Html.BeginForm("DeleteIncidentEvent", "IncidentEvent", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.IncidentEventID)
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Incident List", "Incidents","Incident", null, null)
        </div>
    }
</div>

Assistability/PresentationMVC/Views/IncidentEvent/IncidentEvents.cshtml
@model IEnumerable<DataStorageModels.IncidentEvent>

@{
    ViewBag.Title = "IncidentEvents";
}

<h2>IncidentEvents</h2>

<p>
    @Html.ActionLink("Create New Incident Event", "Create", "IncidentEvent" , new { ViewBag.IncidentName } ,null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IncidentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfOccurence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PersonsInvolved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventConsequence)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IncidentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfOccurence)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PersonsInvolved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventConsequence)
        </td>
        <td>
            @Html.ActionLink("Delete Incident Event", "Delete", "IncidentEvent", new { item.IncidentEventID }, null)
        </td>
    </tr>
}

</table>
<p>@Html.ActionLink("Back to Incidents","Incidents","Incident")</p>