Assistability/PresentationMVC/Models/GroupMemberListViewModel.cs
/// <summary>
/// William Clark
/// Created: 2021/04/24
/// 
/// View Model for GroupMemberList include two lists of UserAccount objects
/// </summary>
///
/// <remarks>
/// </remarks>
using DataStorageModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationMVC.Models
{
    public class GroupMemberListViewModel
    {
        public string FirstListRole { get; set; }
        public List<UserAccount> FirstList { get; set; }
        public string SecondListRole { get; set; }
        public List<UserAccount> SecondList { get; set; }

        public GroupMemberListViewModel()
        {
            FirstList = new List<UserAccount>();
            SecondList = new List<UserAccount>();
        }

        public GroupMemberListViewModel(string firstListRole, List<UserAccount> firstList, string secondListRole, List<UserAccount> secondList)
        {
            FirstListRole = firstListRole;
            FirstList = firstList;
            SecondListRole = secondListRole;
            SecondList = secondList;
        }
    }
}

Assistability/PresentationMVC/Controllers/GroupMemberListController.cs
using DataStorageModels;
using DataViewModels;
using LogicLayer;
using LogicLayerInterfaces;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PresentationMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationMVC.Controllers
{
    public class GroupMemberListController : Controller
    {
        /// <summary>
        /// William Clark
        /// Created: 2021/04/25
        ///
        /// Action method for returning the GroupMemberList view. 
        /// </summary>
        /// 
        ///<returns>The GroupMemberList view with two lists composed of the UserAccounts which belong to the same groups as the currently authenticated user, and which are assigned roles that the UserAccount does not have.</returns>
        [HttpGet]
        public ActionResult GroupMemberList()
        {
            IUserGroupManager oldUserGroupManager = new UserGroupManager();
            IUserManager oldUserManager = new UserManager();
            try
            {
                var newUserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

                var roles = newUserManager.GetRolesAsync(User.Identity.GetUserId()).Result;
                UserAccountVM oldUserVM = AccountController.GetAuthenticatedUserAccountVM(HttpContext);

                if (roles.Contains("Client"))
                {
                    List<UserAccount> firstList = new List<UserAccount>();
                    List<UserAccount> secondList = new List<UserAccount>();
                    foreach (var membership in oldUserVM.Memberships)
                    {
                        firstList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Admin"));
                        secondList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Caregiver"));
                    }
                    return PartialView(new GroupMemberListViewModel("Admin", firstList, "Caregiver", secondList));
                }
                else if (roles.Contains("Caregiver"))
                {
                    List<UserAccount> firstList = new List<UserAccount>();
                    List<UserAccount> secondList = new List<UserAccount>();
                    foreach (var membership in oldUserVM.Memberships)
                    {

                        firstList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Client"));
                        secondList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Admin"));
                    }
                    return PartialView(new GroupMemberListViewModel("Client", firstList, "Admin", secondList));
                }
                else // User is an Admin
                {
                    List<UserAccount> firstList = new List<UserAccount>();
                    List<UserAccount> secondList = new List<UserAccount>();
                    foreach (var membership in oldUserVM.Memberships)
                    {

                        firstList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Client"));
                        secondList.AddRange(oldUserGroupManager.GetUserAccountsInUserGroupByRole(oldUserManager, oldUserGroupManager.GetUserGroupByGroupID(membership.GroupID), "Caregiver"));
                    }
                    return PartialView(new GroupMemberListViewModel("Client", firstList, "Caregiver", secondList));
                }
            }
            catch
            {
                return PartialView(new GroupMemberListViewModel());
            }
        }

        /// <summary>
        /// William Clark
        /// Created: 2021/04/25
        ///
        /// Controller method to invoke from views to alter selected user 
        /// </summary>
        
        public void ResolveSelectedGroupMember(string id)
        {
            IUserManager oldUserManager = new UserManager();
            UserAccount userAccount;
            try
            {
                userAccount = oldUserManager.GetUserAccountByUserAccountID(int.Parse(id));
            }
            catch (Exception)
            {
                userAccount = AccountController.GetAuthenticatedUserAccount(HttpContext);
            }
            if (Session["SelectedUser"] == null)
            {
                Session.Add("SelectedUser", userAccount.UserAccountID.ToString());
            }
            else
            {
                Session["SelectedUser"] = userAccount.UserAccountID.ToString();
            }
            if (!Request.UrlReferrer.OriginalString.Contains("Dashboard"))
            {
                Response.Redirect(Request.UrlReferrer.AbsoluteUri);
            }
            else
            {
                Response.Redirect(Request.UrlReferrer.AbsoluteUri.Trim("Dashboard".ToCharArray()));
            }
        }
    }
}

Assistability/PresentationMVC/Views/Shared/GroupMemberList.cshtml
@model PresentationMVC.Models.GroupMemberListViewModel
@switch (Model.FirstList.Count + Model.SecondList.Count)
{
    case 0:
        // User does not belong to a group with any other members
        break;
    default:
        <div class="grouplist row col-md-9">
            @Html.Label(Model.FirstListRole)
            @foreach (var user in Model.FirstList)
            {
                @Html.ActionLink(@Html.DisplayFor(modelItem => user.FirstName) + " " + @Html.DisplayFor(modelItem => user.LastName), "ResolveSelectedGroupMember", "GroupMemberList", new { id = user.UserAccountID  }, new { @class = "btn btn-primary" })

            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Add", "RegisterToGroup", "Account", null, new { @class = "float-right btn btn-primary" })
            }

        </div>
        <div class="grouplist row col-md-9">
            @Html.Label(Model.SecondListRole)
            @foreach (var user in Model.SecondList)
            {
                @Html.ActionLink(@Html.DisplayFor(modelItem => user.FirstName) + " " + @Html.DisplayFor(modelItem => user.LastName), "ResolveSelectedGroupMember", "GroupMemberList", new { id = user.UserAccountID }, new { @class = "btn btn-primary" })
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Add", "RegisterToGroup", "Account", null, new { @class = "float-right btn btn-primary" })
            }
        </div>
        break;

}

Assistability/PresentationMVC/Views/Shared/_Layout.cshtml
@*
    <remarks>
    Jory A. Wernette
    Created: 2021-04-29

    Background-image and favicon
    </ remarks>

    <remarks>
    Jory A. Wernette
    Created: 2021-05-06

    Added IsAuthenticated get to the Dashboard link
    </ remarks>
*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assistability</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/CalendarStyle.css" rel="stylesheet" />
    <link href="~/Content/CalendarTheme.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/grouplist.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />

</head>
<body style="background-image: url('../../images/background-image-swoosh.png');">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("My Dashboard", "Dashboard", "Home", null, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Administration", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @* <summary>
        Nathaniel Webber
        Created: 2021-04-23

        Added Calendar
        </ summary>
        <notes>
        Nathaniel Webber
        Date: 2021-04-28
        Re-added Calendar after accidental deletion
        </ notes>*@
    @if (Request.IsAuthenticated)
    {
        <div id="rightColumn" class="column">
            <div class="calendar" id="calendar"></div><br /><br /><br /><br />
            <div id="routineCalendarDiv">
                @Html.Action("RoutinePartial", "Routine")
            </div>
        </div>
    }


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Assistability</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
    <script src="~/Scripts/calendar.min.js"></script>
    <script src="~/Scripts/grouplist.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>